# ROLE
# ----
# Seuils conservateurs utilisés pour écarter un audio avant le matching coranique.

NON_ARABIC_LANGUAGE_MIN_PROBABILITY = 0.75
NON_ARABIC_MAX_ARABIC_PROBABILITY = 0.15

MIN_AVERAGE_LOG_PROBABILITY = -1.0
HIGH_TEMPERATURE = 0.8
HIGH_TEMPERATURE_MAX_LOG_PROBABILITY = -0.8
HIGH_COMPRESSION_RATIO = 2.4
HIGH_COMPRESSION_MAX_LOG_PROBABILITY = -0.7
